(require 'color-theme)
(color-theme-twilight)
(global-set-key (kbd "C-z") 'undo)
(global-set-key (kbd "<M-left>") 'windmove-left)
(global-set-key (kbd "<M-right>") 'windmove-right)
(global-set-key (kbd "<M-up>") 'windmove-up)
(global-set-key (kbd "<M-down>") 'windmove-down)
(global-set-key (kbd "<C-prior>") 'next-buffer)
(global-set-key (kbd "<C-next>") 'previous-buffer)
(global-set-key (kbd "C-o") 'find-file-at-point)
